#!/usr/bin/#!/usr/bin/env bash

#color prompt preview
red="\033[00;31m"
black="\e[30m"
green="\e[32m"
yellow="\e[33m"
blue="\e[34m"
lgreen="\e[92m"
cyan="\e[96m"
magenta="\e[35m"
lgrey="\e[37m"
dgrey="\e[90m"
lred="\e[91m"
lgreen="\e[92m"
lyellow="\e[93m"
lblue="\e[94m"
lmagenta="\e[95m"
lcyan="\e[96m"
white="\e[97m"

default="\e[39m"
restore="\033[0m"
end="\e[0m"
bold="\e[1m"
unerline="\e[4m"
clear
#echo -en "[${green}name$restore${lblue}@${default}host $yellow dir$end]"
echo -en "[${lgreen}`whoami`$restore${lblue}@${default}`hostname` $lyellow`echo "${PWD##*/}"
`$end]\n"
